<?php

// HTTP STATUS CODE
define('HTTP_STATUS_OK', 200);
define('HTTP_STATUS_CODE_CREATED', 201);
define('HTTP_STATUS_CODE_BAD_REQUEST', 400);
define('HTTP_STATUS_CODE_UNAUTHORIZED', 401);
define('HTTP_STATUS_CODE_FORBIDDEN', 403);
define('HTTP_STATUS_CODE_NOT_FOUND', 404);
define('HTTP_STATUS_CODE_METHOD_NOT_ALLOWED', 405);
define('HTTP_STATUS_CODE_FAILED', 500);
define('HTTP_STATUS_CODE_SERVICE_UNAVAILABLE', 503);

define('RES_SUCCESS', 1);
define('RES_FAILD', 0);